### ISSUE TITLE
Add custom MakeFilesystemStep instead of compiling an executable

### ISSUE THREAD

**Issue by binarycraft007** [snoire/xv6-zig#1]
Hi snoire,

I am working on xv6-zig too, wanna share some of my findings.

In https://github.com/snoire/xv6-zig/blob/zig/build.zig#L132, mkfs.zig is compiled to binary, and used to generate fs.img, more ziggy way is to add a custom build step: e.g., https://github.com/binarycraft007/xv6-riscv-zig/blob/main/Build/MakeFilesystemStep.zig.

**Comment by snoire** [comment]
Thank you for your suggestion. But now, I would like to keep the project as consistent as possible with the original code. I am currently focused on completing the project and will reconsider optimization strategies once it is finalized.

Thanks again for your valuable input! Let me know if you have any other suggestions or feedback.

**Comment by binarycraft007** [comment]
> Thank you for your suggestion. But now, I would like to keep the project as consistent as possible with the original code. I am currently focused on completing the project and will reconsider optimization strategies once it is finalized.
> 
> Thanks again for your valuable input! Let me know if you have any other suggestions or feedback.

hi, snoire, nothing so far, great job for implementing the PageAllocator in zig style

**Comment by snoire** [comment]
You're welcome!
